POST http://localhost:4000/app/users
Content-Type: application/json
{
    
"Name": "Rahul Nair",
Email: "rahul@gmail.com",
"AcNo": "2000",
"Balance": "20000",


}
{
    
"Name": "Deepak Nair",
Email: "deepak@gmail.com",
"AcNo": "5000",
"Balance": "30000",


}